services:
  syntheticvitalsdemo:
    image: ${DOCKER_REGISTRY-}syntheticvitalsdemo
    build:
      context: .
      dockerfile: SyntheticVitalsDemo.Api/Dockerfile
    env_file:
      - SyntheticVitalsDemo.Api/local.env
