// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SyntheticVitalsDemo.Api.Data;

#nullable disable

namespace SyntheticVitalsDemo.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528000000_AddSeatedAndSupinePulmonaryPressures")]
    partial class AddSeatedAndSupinePulmonaryPressures
    {
    }
}
