// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyntheticVitalsDemo.Api.Data;

#nullable disable

namespace SyntheticVitalsDemo.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DiastolicBp")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("SeatedPaDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("SeatedPaMean")
                        .HasColumnType("int");

                    b.Property<int>("SeatedPaSystolic")
                        .HasColumnType("int");

                    b.Property<int>("SupinePaDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("SupinePaMean")
                        .HasColumnType("int");

                    b.Property<int>("SupinePaSystolic")
                        .HasColumnType("int");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<int>("Spo2")
                        .HasColumnType("int");

                    b.Property<int>("SystolicBp")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightLbs")
                        .HasPrecision(6, 1)
                        .HasColumnType("decimal(6,1)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.VitalsSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DiastolicBp")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("SeatedPaDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("SeatedPaMean")
                        .HasColumnType("int");

                    b.Property<int>("SeatedPaSystolic")
                        .HasColumnType("int");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("varchar(48)");

                    b.Property<int>("Spo2")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SupinePaDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("SupinePaMean")
                        .HasColumnType("int");

                    b.Property<int>("SupinePaSystolic")
                        .HasColumnType("int");

                    b.Property<int>("SystolicBp")
                        .HasColumnType("int");

                    b.Property<string>("TrendScenario")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("WeightLbs")
                        .HasPrecision(6, 1)
                        .HasColumnType("decimal(6,1)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "SubmittedAtUtc");

                    b.ToTable("VitalsSubmissions");
                });

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.Patient", b =>
                {
                    b.HasOne("SyntheticVitalsDemo.Api.Models.Clinic", "Clinic")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.VitalsSubmission", b =>
                {
                    b.HasOne("SyntheticVitalsDemo.Api.Models.Patient", "Patient")
                        .WithMany("VitalsSubmissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.Clinic", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("SyntheticVitalsDemo.Api.Models.Patient", b =>
                {
                    b.Navigation("VitalsSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
